# Generated by Django 5.0.2 on 2024-03-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks_web', '0001_initial'),
    ]

 
